[package]
name = "dcc-bigfred-proto-z21-server"
description = "Experimental Z21 UDP server (std)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
dcc-bigfred-proto-z21.workspace = true
heapless.workspace = true
